### ISSUE TITLE
[feature] Improve console output

### ISSUE THREAD

**Issue by tomav** [instabot42/instabot-trader#2]
The console output is (too) verbose.
What I propose:

- [ ] have a `debug` param, default to `0`, to get verbose mode disabled by default
- [ ] change the default console output to something more generic, prefixed by a timestamp

What do you think about that?

**Comment by tomav** [comment]
Same verbosity also applies to notifications:

```
*-bot, [23 nov. 2018 à 19:31:14]:
OK. I'll try and deal with that. I'll let you know when it's done... 👍

Just finished working on
deribit(BTC-PERPETUAL) {
    stopMarketOrder(side=sell, amount=1, offset=50)
}
🤞
```

**Comment by instabot42** [comment]
There is a config value, called `logLevel` that controls the console output. 0 is pretty much nothing, 1 is basic progress and 2 has all the api responses etc.
