### ISSUE TITLE
Targetting "tagged" orders seem to work only in the same flow

### ISSUE THREAD

**Issue by tomav** [instabot42/instabot-trader#5]
```
deribit(BTC-PERPETUAL) {
  limitOrder(side=buy, amount=1, offset=5%, tag=plop);
  stopMarketOrder(side=sell, amount=3, offset=10%, tag=plop)
}

deribit(BTC-PERPETUAL) {
  cancelOrders(tagged, plop);
}
```

Output:
* first command executed correctly
* second command (cancelOrders) does not remove orders (this is the issue).

That said, if I merge commands like this:

```
deribit(BTC-PERPETUAL) {
  limitOrder(side=buy, amount=1, offset=5%, tag=plop);
  stopMarketOrder(side=sell, amount=3, offset=10%, tag=plop)
  wait(2s);
  cancelOrders(tagged, plop);
}
```

It works, but not suitable in a strategy flow.

**Comment by tomav** [comment]
Looking at the code, it seems to be the expected behavior.
I suppose tagging is not stored locally, and nor stored neither in the exchange, so the information is lot if not triggered in the same sequence.

Could you confirm?

**Comment by instabot42** [comment]
That is correct. It is only valid inside the current session. I will update the docs to make this clearer.

You can work around this to do what you are trying to do like so...

```
deribit(BTC-PERPETUAL) {
  limitOrder(side=buy, amount=1, offset=5%, tag=plop);
  stopMarketOrder(side=sell, amount=3, offset=10%, tag=plop)
  wait(24h);
}

deribit(BTC-PERPETUAL) {
  cancelOrders(tagged, plop);
}
```

the `wait` will keep the session active for 24 hours (make it 1000 hours if needed), so when you later trigger the second command it will reuse the existing session and find the order. Clearly you need to wait for 'long enough' which isn't perfect, but might well get you over the line. Keep in mind that if the bot is restarted, all session data is lost also.
